source 'https://rubygems.org'

# Specify your gem's dependencies in nagyo-worker.gemspec
gemspec

group :development, :test do
  # public github repo
  gem "nv_helpers", :github => "poblahblahblah/nv_helpers"
  gem "nagyo-server-helper", :path => "../nagyo-server-helper"
  #:branch => "develop"
end
