source 'https://rubygems.org'

# Specify your gem's dependencies in nagyo-worker.gemspec
gemspec

# override to pull from private repo - need your github ssh keys available
gem "nv_helpers", :git => "git@github.com:poblahblahblah/nv_helpers.git"
