require 'rubygems'
source 'http://rubygems.org'

gem 'mongo'
gem 'will_paginate'
gem 'execjs'
gem 'therubyracer'
gem 'rails', '3.1.3'
gem 'will_paginate'
gem 'json'
gem 'has_scope', '0.5.1'
gem 'bson_ext'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

source 'http://gemcutter.org'
gem "mongo_mapper"
gem "formtastic"

source  'http://gems.github.com'
gem 'mattetti-googlecharts'

