require 'rubygems'
source 'http://rubygems.org'

# we are using Ruby 1.9
#ruby "1.9.3"

# use the latest 3.2.x rails
gem 'rails', '~> 3.2.8'
gem 'execjs'
gem 'therubyracer'
gem 'jquery-rails'

gem 'json'
gem "mongoid"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'

  gem 'bootstrap-sass', '~> 2.1.0.0'
end

# need this in all groups for seeding db ...
gem "factory_girl_rails"

# for testing:
group :development, :test do
  gem "rspec-rails", "~> 2.0"
  gem "factory_girl_rails"

  # for running tests as files change: ./script/watchr.rb
  gem "watchr"

  # generate model diagrams: bundle exec rake diagram:all
  gem "railroady"
end

group :test do
  gem "capybara"
  gem "database_cleaner"
  gem "mongoid-rspec"
  gem "shoulda"

  #gem "email_spec"
  gem "cucumber-rails", :require => false
end


# Auth with devise + users in mongodb
gem "devise"

# Deploy with Capistrano
# gem 'capistrano'

#source  'http://gems.github.com'
#gem 'mattetti-googlecharts'

#
gem "rails_admin"

# try generating slugs ala friendly-id for mongo-db
gem "mongoid_slug", :github => "digitalplaywright/mongoid-slug"
